# Change these first
owner: studionuuk # Your GitHub organization or username, where this repository lives
repo: nuuktime # The name of this repository

sites:
  - name: Sols Vivants
    url: https://www.solsvivants.org/
  - name: Sparfell
    url: https://www.sparfell.aero/
  - name: Drive to Zero
    url: https://www.drivetozero.fr/
  - name: LinkUp Factory
    url: 	https://linkupfactory.com/
  - name: Tennis Majors
    url: 	https://www.tennismajors.com/
  - name: MagicRPM
    url: https://www.magicrpm.com/
  - name: Serieously
    url: https://www.serieously.com/
  - name: Delpierre
    url: https://www.delpierre.com/
  - name: Labeyrie
    url: https://www.labeyrie.com/
  - name: Viebois
    url: https://viebois-champdieu.fr/
  - name: Scrine Production
    url: https://scrineprod.fr/
  - name: Thierry Aldeguer
    url: https://aldeguer-thierry-avocat.fr/
  - name: Studio Nuük
    url: https://nuuk.fr/
  - name: Uxo
    url: https://with-uxo.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nuuk.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Statuts Studio Nuük
  introTitle: "**NuukTime** est l'outil de monitoring du Studio Nuük pour les sites que nous administrons."
  introMessage: Cette page référence les sites que nous monitorons.
  navbar:
    - title: Statuts
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
